### ISSUE TITLE
future Date:

### ISSUE THREAD

**Issue by r2evans** [qlcal/qlcal-r#1]
https://github.com/qlcal/qlcal-r/blob/master/DESCRIPTION#L5 lists the date as later this month, should that be `-01-21`?

```
Version: 0.0.2
Date: 2022-02-21
Author: Dirk Eddelbuettel; the authors and contributors of QuantLib
```

**Comment by eddelbuettel** [comment]
Whoops.  Department of typos calling.  Looks like CRAN does not have it, yet my (local) CRAN tarball does.  Odd.

Will fix before the next upload :)

**Comment by r2evans** [comment]
Well, they *kinda* have it: https://github.com/cran/qlcal/blob/master/DESCRIPTION#L5

**Comment by eddelbuettel** [comment]
Good catch taking a look at the mirror.

The dates at CRAN are from the tarball we upload. If none is in there (not a required field) no issue.  They usually nag when it is wrong, eg Uwe caught me recently uploading RcppArmadillo with a 2021 date. Whoops. Rinse and repeat.

So I think here I guess someone at CRAN _may_ have done a gentle post-processing?  Actual GitHub repo, tarball, and GitHub CRAN mirror can't all lie :)
