### ISSUE TITLE
advanceDate increments through the calendar days, not business days 

### ISSUE THREAD

**Issue by YuriWerewolf** [qlcal/qlcal-r#3]
Examples

    advanceDate(tradeDates[1], days = 1)
[1] "2017-01-21"

    advanceDate(tradeDates[1], days = 11)
[1] "2017-01-31"

**Comment by eddelbuettel** [comment]
You need to make sure you have a calendar objects set.  Starting from the code in the README using the NYSE calendar:

```r
> library(qlcal)
> setCalendar("UnitedStates/NYSE")
> getHolidays(as.Date("2022-01-01"), as.Date("2022-12-31"))
[1] "2022-01-17" "2022-02-21" "2022-04-15" "2022-05-30" "2022-06-20"
[6] "2022-07-04" "2022-09-05" "2022-11-24" "2022-12-26"
> advanceDate(as.Date("2022-01-16"), 0) # because we now know 2022-01-17 is a holiday we move twp
[1] "2022-01-18"
> advanceDate(as.Date("2022-01-23"), 1)   # one week later we advance by 1
[1] "2022-01-19"
> 
```

**Comment by YuriWerewolf** [comment]
Thanks for reply Dirk,

That's what I get on my machine, different and inconsistent behavior for different years?

> setCalendar("UnitedStates/NYSE")
> getHolidays(as.Date("2022-01-01"), as.Date("2022-12-31"))
[1] "2022-01-17" "2022-02-21" "2022-04-15" "2022-05-30" "2022-06-20" "2022-07-04"
[7] "2022-09-05" "2022-11-24" "2022-12-26"
> advanceDate(as.Date("2022-01-16"), 0)
[1] "2022-01-18"
> advanceDate(as.Date("2017-01-20"), 0)
[1] "2017-01-20"
> advanceDate(as.Date("2017-01-20"), 1)
[1] "2017-01-21"
> advanceDate(as.Date("2017-01-20"), 2)
[1] "2017-01-22"
> advanceDate(as.Date("2017-01-20"), 3)
[1] "2017-01-23"
> advanceDate(as.Date("2017-01-20"), 4)
[1] "2017-01-24"
> advanceDate(as.Date("2017-01-20"), 5)
[1] "2017-01-25"
> advanceDate(as.Date("2017-01-20"), 6)
[1] "2017-01-26"
> advanceDate(as.Date("2017-01-20"), 7)
[1] "2017-01-27"
> advanceDate(as.Date("2022-01-23"), 1)
[1] "2022-01-25"
> advanceDate(as.Date("2022-01-24"), 1)
[1] "2022-01-25"
> advanceDate(as.Date("2022-01-22"), 1)
[1] "2022-01-25"
> advanceDate(Sys.Date(), 2)
[1] "2022-12-14"
> Sys.Date()
[1] "2022-12-10"
> advanceDate(Sys.Date(), 0)
[1] "2022-12-12"
> getHolidays(as.Date("2017-01-01"), as.Date("2017-12-31"))
[1] "2017-01-02" "2017-01-16" "2017-02-20" "2017-04-14" "2017-05-29" "2017-07-04"
[7] "2017-09-04" "2017-11-23" "2017-12-25"

**Comment by eddelbuettel** [comment]
That is difficult to follow.  Can you maybe do me the favour of formatting that properly (code block for start with three ` backticks followed by r, and end with three backticks) and maybe insert comments about what you expected, and what you got?

**Comment by eddelbuettel** [comment]
I have to look at this some more: given how I document the function I should probably use `advanceUnits` for "Days" here.

You goal is to start with a business day and advance any number of desired days and land on another business day?

**Comment by eddelbuettel** [comment]
Yes, this looks better.  I now use an _advance_ rather than _adjust_ method.  It will also give us more options.  New behaviour:

```r
> setCalendar("UnitedStates/NYSE")
> d <- as.Date("2022-01-14")
> sapply(0:7, function(dt) format(advanceDate(d, dt)))
[1] "2022-01-14" "2022-01-18" "2022-01-19" "2022-01-20" "2022-01-21" "2022-01-24" "2022-01-25" "2022-01-26"
> 
```

"Zero busisness days ahead of Fri Jan 14 is Jan 14" -- correct
"One business day ahead of Fri Jan 14 is Jan 18 as the 17th is holiday in this calendar" -- correct
....
and so on to the next weekend.  Will commit this (once I check and adjust as needed any tests). I also  think I need to add new 'text to int' parser helper for the unit and business day convention.

**Comment by YuriWerewolf** [comment]
Dirk, in the above examples behavior is inconsistent between 2017 and 2022 years. 
For 2017 the function just gives next calendar day, for 2022 it looks like it gives next business day.

Same format, 2017-01-20 was Friday but the results are:
advanceDate(as.Date("2017-01-20"), 0)
[1] "2017-01-20"
advanceDate(as.Date("2017-01-20"), 1)
[1] "2017-01-21"
advanceDate(as.Date("2017-01-20"), 2)
[1] "2017-01-22"
advanceDate(as.Date("2017-01-20"), 3)
[1] "2017-01-23"

**Comment by eddelbuettel** [comment]
I have no idea what you are trying to say here.  Talk to me like I am five: what did you do (I see that), what did you expect (we are missing that), what if anything is your working hypothesis.

And the example still isn't formatted.  Maybe take a look a [this](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) -- it's worth learning some basics.

**Comment by eddelbuettel** [comment]
Also when you comparing between years make sure you to either pick invariant holidays (July 4, Dec 25, ...) or to ensure you have a correct one.  Many holidays in the NYSE calendar 'roll' to the relevant Monday, say, as observed date.  So MLK Jr Day may have been Jan 17 _this year_ but that does _not_ mean it is Jan 17 _every year_.  And QuantLib is very, very good at getting that right.

**Comment by eddelbuettel** [comment]
Closing because of lack of follow-up.
