### ISSUE TITLE
Update HongKong calendar to post-QuantLib 1.30 changes

### ISSUE THREAD

**Issue by oldirtybasti** [qlcal/qlcal-r#4]
I just realised that qlcal is based on quantlib 1.24 and some of the calendars (like ASX) on 1.30. The Hong Kong holidays are still from 1.24. QuantLib does not implement a lunar calendar and therefore has to hardcode all holidays that are based on the lunar calendar (mostly an issue with Asian markets).

Would be nice to update the HongKong calendar to the current QuantLib release.

**Comment by eddelbuettel** [comment]
I think you are mistaken -- just look at the NEWS file, or ChangeLog, or commit history:

https://github.com/qlcal/qlcal-r/blob/0020aaac2a0f9922b293e9d3e83319798162b1ec/inst/NEWS.Rd#L6-L13

Where is your qlcal from?  Binary package you did not update?  Build from source?  CRAN is current too:

![image](https://github.com/qlcal/qlcal-r/assets/673121/4008ace9-284b-42c7-bc90-bd7a7e29ebf2)

**Comment by oldirtybasti** [comment]
I use the latest version of qlcal from github.

other attached packages:
[1] qlcal_0.0.5.1


You can reproduce the error by the following script.
```
setCalendar("HongKong")
getHolidays(as.Date("2023-01-01"), as.Date("2023-12-31"))
```
[1] "2023-01-02" "2023-04-07" "2023-04-10" "2023-05-01" "2023-10-02" "2023-12-25" "2023-12-26"

Compare that with the latest hongkong.cpp from quantlib (line 368++)

```
        // data from https://www.hkex.com.hk/-/media/HKEX-Market/Services/Circulars-and-Notices/Participant-and-Members-Circulars/SEHK/2022/ce_SEHK_CT_058_2022.pdf
        if (y == 2023)
        {
            if (// Lunar New Year
                ((d >= 23 && d <= 25) && m == January)
                // Ching Ming Festival
                || (d == 5 && m == April)
                // Buddha's birthday
                || (d == 26 && m == May)
                // Tuen Ng festival
                || (d == 22 && m == June)
                // Chung Yeung festival
                || (d == 23 && m == October))
                return false;
        }
```
which does implement the 2023 lunar based holidays (like Chinese New Year)

**Comment by eddelbuettel** [comment]
Thanks so much for #5 and #6.  This is now taken care of.

**Comment by eddelbuettel** [comment]
Thanks again -- new version now at CRAN.
